services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: calculatorGCC_nginx_dev
    depends_on:
      - backend
      - frontend
      - phpmyadmin
    environment:
      NODE_PROJET: dev
      ENABLE_SSL: ${ENABLE_SSL:-true}
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/conf/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ssl_certs:/etc/nginx/ssl
    restart: unless-stopped
    networks:
      - calculatorGCC_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: calculatorGCC_backend_dev
    environment:
      NODE_ENV: development
      PORT: 7000
      HOSTNAME: ${HOSTNAME:-localhost}
      ENABLE_SSL: ${ENABLE_SSL:-false}
    ports:
      - "9229:9229"  # Port pour le d√©bogage
    volumes:
      - ./backend/srcs:/app:delegated
      - /app/node_modules
    working_dir: /app
    restart: unless-stopped
    networks:
      - calculatorGCC_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: calculatorGCC_frontend_dev
    environment:
      NODE_ENV: development
      VITE_HOSTNAME: ${HOSTNAME:-localhost}
      VITE_ENABLE_SSL: ${ENABLE_SSL:-false}
    volumes:
      - ./frontend/srcs:/app:delegated
      - /app/node_modules
    working_dir: /app
    restart: unless-stopped
    networks:
      - calculatorGCC_network

  mariadb:
    image: mariadb:latest
    container_name: calculatorGCC_mariadb_dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME:-calculatorgcc}
      MYSQL_USER: ${DB_USER:-calculatorgcc_user}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - calculatorGCC_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: calculatorGCC_phpmyadmin_dev
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      UPLOAD_LIMIT: 50M
      PMA_ABSOLUTE_URI: ${HOSTNAME:-localhost}:3000/phpmyadmin/
    restart: unless-stopped
    networks:
      - calculatorGCC_network

networks:
  calculatorGCC_network:
    driver: bridge

volumes:
  ssl_certs:
  mariadb_data:
